"""Add company profile table

Revision ID: 0a144e913bf2
Revises: 7a836fb59f86
Create Date: 2025-11-09 17:39:49.964701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a144e913bf2'
down_revision = '7a836fb59f86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


